export enum ROUTES_NAME {
  APP_NAVIGATOR = 'APP_NAVIGATOR',
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
  TAB_NAVIGATOR = 'TAB_NAVIGATOR',

  INITIAL_SCREEN = 'INITIAL_SCREEN',
  HOME_SCREEN = 'HOME_SCREEN',
  FAVORITES_SCREEN = 'FAVORITES_SCREEN',
  CART_SCREEN = 'CART_SCREEN',
}
